### ISSUE TITLE
Cannot build with HHVM 3.9.0

### ISSUE THREAD

**Issue by doublecompile** [mongofill/mongofill-hhvm#42]
It appears the `IniSetting` class has changed between HHVM 3.8.1 and HHVM 3.9.0.

When I run `./build.sh`, it fails with the following:

```
make
Scanning dependencies of target mongo
[ 33%] Building CXX object CMakeFiles/mongo.dir/src/bson.cpp.o
/tmp/builds/mongofill-hhvm/src/bson.cpp: In member function ‘virtual void HPHP::mongoExtension::moduleLoad(const Map&, HPHP::Hdf)’:
/tmp/builds/mongofill-hhvm/src/bson.cpp:78:24: error: ‘const Map’ has no member named ‘get_ptr’
     auto ini_val = ini.get_ptr("apc.enable");
                        ^
make[2]: *** [CMakeFiles/mongo.dir/src/bson.cpp.o] Error 1
make[1]: *** [CMakeFiles/mongo.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by ProdigyView** [comment]
Yea, same problem here

**Comment by steelbrain** [comment]
Bump.
