### ISSUE TITLE
can't compile on mac osx 10.10.5

### ISSUE THREAD

**Issue by taylor19882002** [mongofill/mongofill-hhvm#49]
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [mongo.so] Error 1
make[1]: *** [CMakeFiles/mongo.dir/all] Error 2
make: *** [all] Error 2

anyone meet before ?

**Comment by wowazzz** [comment]
I guess no one can built any extension on MacOS
[https://github.com/hhvm/homebrew-hhvm/issues/81](url)
