### ISSUE TITLE
can't compile in ubuntu 14.04.1

### ISSUE THREAD

**Issue by fizzka** [mongofill/mongofill-hhvm#19]
./build.sh trace:
```shell
...
Scanning dependencies of target mongo
[ 33%] Building CXX object CMakeFiles/mongo.dir/src/bson.cpp.o
[ 66%] Building CXX object CMakeFiles/mongo.dir/src/encode.cpp.o
/home/fizzka/projects/mongofill-hhvm/src/encode.cpp: In function ‘void HPHP::objectToBSON(const HPHP::Object&, const char*, bson_t*)’:
/home/fizzka/projects/mongofill-hhvm/src/encode.cpp:86:36: error: ‘class HPHP::ObjectData’ has no member named ‘getClassName’
   const String& className = value->getClassName();
                                    ^
make[2]: *** [CMakeFiles/mongo.dir/src/encode.cpp.o] Error 1
make[1]: *** [CMakeFiles/mongo.dir/all] Error 2
make: *** [all] Error 2

hhvm --version
HipHop VM 3.4.2 (rel)
Compiler: tags/HHVM-3.4.2-0-g40d85d7386b3342ab848fc45c6892433c89ef5b2
Repo schema: 13cba877c4300d1d0481b3f40eb128a5115d4e08
Extension API: 20140829
```

libbson: from master #ada52d0

**Comment by eeertekin** [comment]
Pull request created for the fix https://github.com/mongofill/mongofill-hhvm/pull/23

### make error
[ 33%] Building CXX object CMakeFiles/mongo.dir/src/encode.cpp.o
/usr/src/mongofill-hhvm/src/encode.cpp: In function ‘void HPHP::objectToBSON(const HPHP::Object&, const char*, bson_t*)’:
/usr/src/mongofill-hhvm/src/encode.cpp:86:36: error: ‘class HPHP::ObjectData’ has no member named ‘getClassName’
   const String& className = value->getClassName();
                                    ^
make[2]: *** [CMakeFiles/mongo.dir/src/encode.cpp.o] Error 1
make[1]: *** [CMakeFiles/mongo.dir/all] Error 2
make: *** [all] Error 2


### hhvm --version
HipHop VM 3.4.2 (rel)
Compiler: tags/HHVM-3.4.2-0-g40d85d7386b3342ab848fc45c6892433c89ef5b2
Repo schema: 13cba877c4300d1d0481b3f40eb128a5115d4e08
Extension API: 20140829

**Comment by Pomyk** [comment]
I pushed a fix, can you test it?

**Comment by fizzka** [comment]
compliled successufully, extension functional.
